name: 📦 Bump Workflow

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: |
          The version to update to (eg: 2.6.0 or 2.6.0-dev do not include `v`).
        required: true 
jobs:

  apply-version-bump:
    runs-on: ubuntu-22.04
    name: Apply Version Bump
    steps:
        - name: Checkout 
          uses: actions/checkout@v3

        - name: Apply Bump
          shell: bash
          run: |
            bash ./scripts/bump_version.sh ${{ github.event.inputs.new_version }}

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v4
          with: 
            title: "Release Engineering: Version bump to ${{ github.event.inputs.new_version }}."
            body: "This PR updates codeql-coding-standards to version ${{ github.event.inputs.new_version }}."
            commit-message: "Version bump to ${{ github.event.inputs.new_version }}."
            delete-branch: true
            branch: "automation/version-bump-${{ github.event.inputs.new_version }}"
